### PR TITLE
Add opacity support

### PR DESCRIPTION
**Pull request by codemers**
We can no specify the opacity of the prompt.

The code was reformatted automatically with prettier

### CODE REVIEW

**Review by SkrewEverything — CHANGES_REQUESTED** [review]
In README.md, for `opacity` you have mentioned a default value as 0.8 and didn't mention `required`.

But in Prompt.js, you have mentioned `opacity: PropTypes.number.isRequired`.

Just change the `opacity: PropTypes.number.isRequired` to `opacity: PropTypes.number`

**Comment by codemers** [comment]
Well the props is required but it's defined in the default props in the prompt.js

**Comment by SkrewEverything** [comment]
@charlot567

The default value of `opacity` is fine. It is not like a `title` or `visible` which depends on the user.

In simple terms, even though `title` and `visible` has a default props, the default value doesn't make any sense which is not true for `opacity`. 

I have tried to match the native OS opacity value. So, the number of developers actually fiddling with the `opacity` prop is very low to none. So, making it `require` is actually a bad idea.

I like your idea of providing the developers an ability to change the `opacity` of the prompt. But the customization you are providing to the developers is very low priority. Even without changing the `opacity`, it provides a meaningful behaviour.

So, if the component is providing meaningful behaviour without passing props  explicitly, it should be made as `optional` just to reduce the burden on the developer. Just like the `cancelText` and `submitText` prop.

**Comment by rudin** [comment]
Great prompt @SkrewEverything!

Definitely need this opacity feature, since for me it's way too transparent by default. Any idea when you can merge this? Thanks!

**Pull request closed without merging**
